name: CD
on:
  push:
    branches: [ master ]
    paths: 
      - '**.py'
      - '**.yml'
  pull_request:
    branches: [ master ]
    paths: 
      - '**.py'
      - '**.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install serverless
      run: npm install -g serverless
    
    - name: Configure serverless
      run: serverless config credentials --provider aws --key ${{ secrets.ACCESS_KEY_ID }} --secret ${{ secrets.SECRETE_ACCESS_KEY }}

    - name: Serverless deploy
      run: serverless deploy
